### ISSUE TITLE
Getting this error trying to start the project (LUA 5.4, LOVE: 11.3)

### ISSUE THREAD

**Issue by ant0nioli** [coetaur0/AdventureGame#1]
Hi, below is is the error I'm getting. Thank you!

Error
engine/entities/actor.lua:46: attempt to call method 'getData' (a nil value)

Traceback
engine/entities/actor.lua:46: in function 'setPositionInRoom'
engine/entities/room.lua:45: in function 'new'
lib/classic.lua:63: in function 'Room'
engine/game.lua:48: in function 'new'
lib/classic.lua:63: in function 'Game'
main.lua:8: in function 'load'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by mal2** [comment]
(Image):getData was removed in löve 11, look at my pull request for a fixed version.

**Comment by coetaur0** [comment]
The pull request does indeed solve the issue with the 'getData' method. I am marking this issue as solved. Thanks for the fix !
